In [ ]:
import gdown
url= 'https://drive.google.com/file/d/1HZcEAbfRQQSgfMB_SEx3Q3vqkqxzcjk-/view?usp=drive_link'
output= 'Camioneta furgon Iveco Daily.json'
gdown.download(url, output, fuzzy=True)

Downloading...
From: https://drive.google.com/uc?id=1HZcEAbfRQQSgfMB_SEx3Q3vqkqxzcjk-
To: /content/Camioneta furgon Iveco Daily.json
100%|██████████| 2.25M/2.25M [00:00<00:00, 120MB/s]

'Camioneta furgon Iveco Daily.json'

In [ ]:
import pandas as pd
import json

# Load the JSON file
with open('Camioneta furgon Iveco Daily.json', 'r') as f:
    data = json.load(f)

# Normalize the 'gral' section of the data (adjust 'gral' if it's a different key)
df_gral = pd.json_normalize(data['gral'])

# If there are other sections in your JSON you want as DataFrames, normalize them similarly.
# For example, if you have a section called 'details':
# df_details = pd.json_normalize(data['details'])

# Now you have DataFrames with consistent column lengths
print(df_gral.head())
print(df_gral.info())

   object                      from                        to mins velmax  \
0    3943  2024-06-08T03:00:00.000Z  2024-06-16T01:25:02.905Z    0     92

  type dvcType    _v objType                              hash  kmRec  \
0  can     BCE  next      18  903fca6541a0c5c728fe263109714425  118.5

   engOnSec  motionTime  canKmRec  canConsL  canL100Km
0     56548       16402       120        23       19.2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   object      1 non-null      int64
 1   from        1 non-null      object
 2   to          1 non-null      object
 3   mins        1 non-null      object
 4   velmax      1 non-null      object
 5   type        1 non-null      object
 6   dvcType     1 non-null      object
 7   _v          1 non-null      object
 8   objType     1 non-null      object
 9   hash        1 non-null      object
 10  kmRec       1 non-null      float64
 11  engOnSec    1 non-null      int64
 12  motionTime  1 non-null      int64
 13  canKmRec    1 non-null      int64
 14  canConsL    1 non-null      int64
 15  canL100Km   1 non-null      float64
dtypes: float64(2), int64(5), object(9)
memory usage: 256.0+ bytes
None

In [ ]:
# Normalize the 'gral' section of the data (adjust 'gral' if it's a different key)
df_trips = pd.json_normalize(data['trips'])
df_trips.head()
df_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   type            62 non-null     object
 1   start           62 non-null     int64
 2   end             62 non-null     int64
 3   events          32 non-null     object
 4   from.lat        31 non-null     float64
 5   from.lng        31 non-null     float64
 6   to.lat          31 non-null     float64
 7   to.lng          31 non-null     float64
 8   lat             31 non-null     float64
 9   lng             31 non-null     float64
 10  idleTime        31 non-null     float64
 11  fuelEnd         30 non-null     object
 12  status          31 non-null     object
 13  dir             31 non-null     object
 14  kmRec           30 non-null     float64
 15  engOnSec        30 non-null     float64
 16  motionTime      30 non-null     float64
 17  canKmRec        30 non-null     float64
 18  canConsL        30 non-null     float64
 19  canL100Km       23 non-null     float64
 20  rows            30 non-null     object
 21  maxSpeed.speed  30 non-null     float64
 22  maxSpeed.date   30 non-null     float64
 23  fuelIni         29 non-null     object
 24  can_mileage     30 non-null     float64
dtypes: float64(16), int64(2), object(7)
memory usage: 12.2+ KB

In [ ]:
# Normalize the 'gral' section of the data (adjust 'gral' if it's a different key)
df_details = pd.json_normalize(data['details'])
df_details.head()
df_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1858 entries, 0 to 1857
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         1858 non-null   int64
 1   bat          1858 non-null   float64
 2   km           1858 non-null   float64
 3   engOn        1858 non-null   bool
 4   evDesc       1858 non-null   object
 5   dir          1858 non-null   object
 6   lat          1857 non-null   float64
 7   lng          1857 non-null   float64
 8   speed        1857 non-null   float64
 9   heading      1857 non-null   float64
 10  wheel_speed  1619 non-null   float64
 11  total_fuel   1619 non-null   float64
 12  can_fls      1619 non-null   float64
 13  can_taho     1619 non-null   float64
 14  can_mileage  1619 non-null   float64
 15  eng_temp     1619 non-null   float64
dtypes: bool(1), float64(12), int64(1), object(2)
memory usage: 219.7+ KB

In [ ]:
df_details.describe()

,date,bat,km,lat,lng,speed,heading,wheel_speed,total_fuel,can_fls,can_taho,can_mileage,eng_temp
count,1.858000e+03,1858.000000,1858.000000,1857.000000,1857.000000,1857.000000,1857.000000,1619.000000,1619.000000,1619.000000,1619.000000,1619.000000,1619.000000
mean,1.718233e+09,14.335358,60.744779,-37.152351,-58.489131,17.292407,166.066774,0.078289,8339.931130,76.200124,1328.208771,51307.938851,73.963558
std,7.408740e+04,0.799845,35.674240,0.004416,0.008655,12.778118,97.806745,0.045449,6.800898,16.117253,398.461764,34.763148,9.662949
min,1.718108e+09,0.000000,0.000000,-37.164100,-58.504000,0.000000,0.000000,0.000000,8328.000000,0.000000,352.000000,51250.000000,8.000000
25%,1.718198e+09,14.499000,30.125000,-37.154700,-58.495800,7.000000,86.000000,0.050781,8334.000000,61.000000,959.500000,51279.000000,76.000000
50%,1.718228e+09,14.553000,61.250000,-37.152600,-58.488700,18.000000,140.000000,0.078125,8340.000000,73.000000,1344.000000,51307.000000,78.000000
75%,1.718293e+09,14.597000,91.400000,-37.149600,-58.482500,26.000000,226.000000,0.109375,8346.000000,97.000000,1621.000000,51338.000000,78.000000
max,1.718394e+09,14.792000,118.500000,-37.141200,-58.467700,62.000000,358.000000,0.234375,8351.000000,99.000000,2494.000000,51369.000000,80.000000

In [ ]:
#ver las correlaciones en mi df
# Calcular las correlaciones con algunas columnas seleccionadas
correlation_matrix = df_details[['km', 'speed', 'total_fuel']].corr()

# Print the correlation matrix
print(correlation_matrix)

                  km     speed  total_fuel
km          1.000000 -0.117584    0.999122
speed      -0.117584  1.000000   -0.003360
total_fuel  0.999122 -0.003360    1.000000